#!/usr/bin/env node
// build-skm.mjs — WSL companion（skm）零依赖单文件 bundle 构建（docs/09 §2/§4.2）。
//
// 源码：src/main/services/skills/skm-src/*.mjs（自 Skill-Manager src/companion/skm.ts
// 复制移植到 DevHub 树内）。产物：<projectRoot>/artifacts/skm.mjs —— deployCompanion
// 经 wsl.exe 把它部署到 WSL /root/skill-vault/bin/skm.mjs。
//
// esbuild 使用依赖树内已有版本（electron-vite → vite 的依赖，docs/09 §11.4 零新增依赖）；
// 本脚本只在开发/部署机上经 `node scripts/build-skm.mjs` 运行（skillService 经
// core/exec 按需调用），不进入 Electron 运行时。
//
// 用法：node scripts/build-skm.mjs [--check]
//   --check  仅校验产物是否最新（mtime 比对），最新则退出 0，过期/缺失退出 1。

import { existsSync, mkdirSync, statSync, readdirSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createRequire } from 'node:module'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SRC_DIR = join(ROOT, 'src', 'main', 'services', 'skills', 'skm-src')
const OUT_DIR = join(ROOT, 'artifacts')
const OUT_FILE = join(OUT_DIR, 'skm.mjs')
const ENTRY = join(SRC_DIR, 'skm.mjs')

const checkOnly = process.argv.includes('--check')

function newestMtime(dir) {
  let newest = 0
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (!e.isFile() || !e.name.endsWith('.mjs')) continue
    const m = statSync(join(dir, e.name)).mtimeMs
    if (m > newest) newest = m
  }
  return newest
}

if (checkOnly) {
  if (!existsSync(OUT_FILE)) {
    console.error('bundle missing:', OUT_FILE)
    process.exit(1)
  }
  if (statSync(OUT_FILE).mtimeMs < newestMtime(SRC_DIR)) {
    console.error('bundle stale:', OUT_FILE)
    process.exit(1)
  }
  console.log('bundle up-to-date:', OUT_FILE)
  process.exit(0)
}

const require = createRequire(import.meta.url)
const esbuild = require('esbuild')

mkdirSync(OUT_DIR, { recursive: true })
const result = await esbuild.build({
  entryPoints: [ENTRY],
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node18',
  minify: false,
  sourcemap: false,
  outfile: OUT_FILE,
  logLevel: 'info',
  absWorkingDir: ROOT,
  banner: {
    // WSL 内以 node 直接执行；ESM 顶层无需特殊处理，banner 仅作来源标注
    js: `// devhub skm companion bundle — generated by scripts/build-skm.mjs, do not edit`,
  },
})

if (result.errors.length > 0) {
  console.error('esbuild failed')
  process.exit(1)
}
console.log('bundle written:', OUT_FILE)
