// devhub skm companion bundle — generated by scripts/build-skm.mjs, do not edit

// src/main/services/skills/skm-src/skm.mjs
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";

// src/main/services/skills/skm-src/registry.mjs
function agentIncludes(include, skillName) {
  return include.includes("*") || include.includes(skillName);
}
function isPlatform(v) {
  return v === "windows" || v === "linux";
}
function parseRegistry(text) {
  let data;
  try {
    data = JSON.parse(text);
  } catch (e) {
    return { ok: false, error: `registry.json \u4E0D\u662F\u5408\u6CD5 JSON: ${String(e)}` };
  }
  if (typeof data !== "object" || data === null) return { ok: false, error: "registry.json \u6839\u8282\u70B9\u5FC5\u987B\u662F\u5BF9\u8C61" };
  const obj = data;
  if (obj.version !== 1 && obj.version !== 2) {
    return { ok: false, error: `registry.json version \u5FC5\u987B\u4E3A 1 \u6216 2\uFF0C\u5B9E\u9645: ${String(obj.version)}` };
  }
  if (!Array.isArray(obj.agents)) return { ok: false, error: "registry.json \u7F3A\u5C11 agents \u6570\u7EC4" };
  const agents = [];
  const seen = /* @__PURE__ */ new Set();
  for (const raw of obj.agents) {
    if (typeof raw !== "object" || raw === null) return { ok: false, error: "agents \u6570\u7EC4\u5B58\u5728\u975E\u5BF9\u8C61\u5143\u7D20" };
    const a = raw;
    if (typeof a.name !== "string" || !a.name.trim()) return { ok: false, error: "agent.name \u5FC5\u987B\u662F\u975E\u7A7A\u5B57\u7B26\u4E32" };
    if (seen.has(a.name)) return { ok: false, error: `agent \u540D\u91CD\u590D: ${a.name}` };
    seen.add(a.name);
    if (!isPlatform(a.platform)) return { ok: false, error: `agent ${a.name} platform \u5FC5\u987B\u4E3A windows|linux` };
    if (typeof a.skillsDir !== "string" || !a.skillsDir.trim()) {
      return { ok: false, error: `agent ${a.name} skillsDir \u5FC5\u987B\u662F\u975E\u7A7A\u5B57\u7B26\u4E32` };
    }
    if (!Array.isArray(a.include) || a.include.length === 0 || !a.include.every((x) => typeof x === "string" && x.trim())) {
      return { ok: false, error: `agent ${a.name} include \u5FC5\u987B\u662F\u975E\u7A7A\u5B57\u7B26\u4E32\u6570\u7EC4\uFF08["*"] \u6216\u6280\u80FD\u540D\u5217\u8868\uFF09` };
    }
    let agentsDir;
    if (a.agentsDir !== void 0) {
      if (typeof a.agentsDir !== "string" || !a.agentsDir.trim()) {
        return { ok: false, error: `agent ${a.name} agentsDir \u5FC5\u987B\u662F\u975E\u7A7A\u5B57\u7B26\u4E32\u6216\u7F3A\u7701` };
      }
      agentsDir = a.agentsDir;
    }
    agents.push({
      name: a.name,
      platform: a.platform,
      skillsDir: a.skillsDir,
      include: a.include,
      ...agentsDir !== void 0 ? { agentsDir } : {}
    });
  }
  return { ok: true, registry: { version: 2, agents } };
}

// src/main/services/skills/skm-src/frontmatter.mjs
function parseFrontmatter(mdText) {
  const text = String(mdText ?? "").replace(/^\uFEFF/, "");
  const lines = text.split(/\r?\n/);
  let i = 0;
  while (i < lines.length && lines[i].trim() === "") i++;
  if (i >= lines.length || lines[i].trim() !== "---") return {};
  i++;
  const out = {};
  for (; i < lines.length; i++) {
    const line = lines[i];
    if (line.trim() === "---") return out;
    const m = line.match(/^(name|description)[ \t]*:[ \t]*(.*)$/);
    if (m === null) continue;
    const key = m[1];
    if (out[key] !== void 0) continue;
    const raw = m[2].trim();
    if (/^[|>][+-]?$/.test(raw)) {
      const { text: block, next } = collectBlockScalar(lines, i + 1, raw);
      i = next - 1;
      if (block) out[key] = stripQuotes(block);
    } else {
      const v = stripQuotes(stripTrailingComment(raw));
      if (v) out[key] = v;
    }
  }
  return {};
}
function stripQuotes(v) {
  if (v.length >= 2) {
    const first = v[0];
    const last = v[v.length - 1];
    if (first === '"' && last === '"' || first === "'" && last === "'") return v.slice(1, -1);
  }
  return v;
}
function stripTrailingComment(v) {
  const hash = v.indexOf(" #");
  return (hash >= 0 ? v.slice(0, hash) : v).trim();
}
function collectBlockScalar(lines, start, indicator) {
  const folded = indicator[0] === ">";
  const parts = [];
  let j = start;
  for (; j < lines.length; j++) {
    const l = lines[j];
    if (l.trim() === "---") break;
    if (l.trim() === "") {
      parts.push("");
      continue;
    }
    if (/^[ \t]/.test(l)) {
      parts.push(l.trim());
      continue;
    }
    break;
  }
  while (parts.length > 0 && parts[parts.length - 1] === "") parts.pop();
  let text = "";
  for (let k = 0; k < parts.length; k++) {
    if (k > 0) text += folded ? parts[k] === "" || parts[k - 1] === "" ? "\n" : " " : "\n";
    text += parts[k];
  }
  return { text: text.trim(), next: j };
}

// src/main/services/skills/skm-src/skm.mjs
var VAULT = process.env.SKM_VAULT || "/root/skill-vault";
var SKILLS_DIR = path.join(VAULT, "skills");
var AGENTS_DIR = path.join(VAULT, "agents");
function emit(obj) {
  process.stdout.write(JSON.stringify(obj) + "\n");
}
function fail(error) {
  emit({ ok: false, error });
  process.exit(1);
}
function gitRun(args) {
  const r = spawnSync("git", args, { cwd: VAULT, encoding: "utf8" });
  return {
    ok: r.status === 0,
    stdout: (r.stdout ?? "").toString(),
    stderr: (r.stderr ?? "").toString()
  };
}
function loadRegistry() {
  const file = path.join(VAULT, "registry.json");
  try {
    const r = parseRegistry(fs.readFileSync(file, "utf8"));
    if (r.ok) return r.registry;
    fail(`registry.json \u89E3\u6790\u5931\u8D25: ${r.error}`);
  } catch (e) {
    fail(`\u65E0\u6CD5\u8BFB\u53D6 registry.json: ${String(e)}`);
  }
}
function listSkills() {
  if (!fs.existsSync(SKILLS_DIR)) return [];
  return fs.readdirSync(SKILLS_DIR, { withFileTypes: true }).filter((e) => e.isDirectory() || e.isSymbolicLink()).map((e) => {
    const hasSkillMd = fs.existsSync(path.join(SKILLS_DIR, e.name, "SKILL.md"));
    let description = "";
    if (hasSkillMd) {
      try {
        description = parseFrontmatter(fs.readFileSync(path.join(SKILLS_DIR, e.name, "SKILL.md"), "utf8")).description ?? "";
      } catch {
        description = "";
      }
    }
    return { name: e.name, hasSkillMd, description };
  }).sort((a, b) => a.name.localeCompare(b.name));
}
function linuxAgents(registry) {
  return registry.agents.filter((a) => a.platform === "linux");
}
function listAgentFiles() {
  if (!fs.existsSync(AGENTS_DIR)) return [];
  return fs.readdirSync(AGENTS_DIR, { withFileTypes: true }).filter((e) => e.isFile() && e.name.toLowerCase().endsWith(".md")).map((e) => e.name).sort((a, b) => a.localeCompare(b));
}
function linkState(linkPath, expected) {
  let st;
  try {
    st = fs.lstatSync(linkPath);
  } catch {
    return "missing";
  }
  if (!st.isSymbolicLink()) return st.isDirectory() ? "real-dir" : "wrong-target";
  let t = "";
  try {
    t = fs.readlinkSync(linkPath);
  } catch {
    return "wrong-target";
  }
  const abs = path.isAbsolute(t) ? t : path.resolve(path.dirname(linkPath), t);
  if (path.resolve(abs) !== path.resolve(expected)) return "wrong-target";
  return fs.existsSync(expected) ? "linked" : "vault-missing";
}
function cmdScan() {
  const registry = loadRegistry();
  const agentFiles = listAgentFiles();
  const agents = [];
  for (const a of linuxAgents(registry)) {
    const links = {};
    for (const s of listSkills()) {
      if (!agentIncludes(a.include, s.name)) continue;
      links[s.name] = linkState(path.join(a.skillsDir, s.name), path.join(SKILLS_DIR, s.name));
    }
    const scan = { name: a.name, platform: "linux", skillsDir: a.skillsDir, links };
    if (a.agentsDir) {
      scan.agentsDir = a.agentsDir;
      scan.agentsDirState = linkState(a.agentsDir, AGENTS_DIR);
      scan.agentFiles = agentFiles;
    }
    agents.push(scan);
  }
  emit({ ok: true, skills: listSkills(), agents, vaultOk: fs.existsSync(path.join(VAULT, ".git")) });
}
function cmdLink(skill, agentName) {
  if (!skill) fail("\u7528\u6CD5: skm link <skill> [--agent <name>]");
  const expected = path.join(SKILLS_DIR, skill);
  if (!fs.existsSync(expected)) fail(`vault \u4E2D\u4E0D\u5B58\u5728 skill: ${skill}`);
  const registry = loadRegistry();
  const results = [];
  for (const a of linuxAgents(registry)) {
    if (agentName && a.name !== agentName) continue;
    if (!agentIncludes(a.include, skill)) continue;
    fs.mkdirSync(a.skillsDir, { recursive: true });
    const linkPath = path.join(a.skillsDir, skill);
    const st = linkState(linkPath, expected);
    if (st === "linked") {
      results.push(`${linkPath} \u5DF2\u94FE\u63A5\uFF0C\u8DF3\u8FC7`);
      continue;
    }
    if (st === "real-dir") {
      results.push(`${linkPath} \u662F\u771F\u5B9E\u76EE\u5F55\uFF0C\u62D2\u7EDD\u8986\u76D6\uFF0C\u8DF3\u8FC7`);
      continue;
    }
    if (st !== "missing") {
      fs.unlinkSync(linkPath);
      results.push(`${linkPath} \u65E7\u94FE\u63A5\u5DF2\u79FB\u9664\uFF08${st}\uFF09`);
    }
    const rel = path.relative(a.skillsDir, expected);
    fs.symlinkSync(rel, linkPath);
    results.push(`${linkPath} -> ${rel}`);
  }
  emit({ ok: true, results });
}
function cmdUnlink(skill, agentName) {
  if (!skill) fail("\u7528\u6CD5: skm unlink <skill> [--agent <name>]");
  const registry = loadRegistry();
  const results = [];
  for (const a of linuxAgents(registry)) {
    if (agentName && a.name !== agentName) continue;
    const linkPath = path.join(a.skillsDir, skill);
    let st;
    try {
      st = fs.lstatSync(linkPath);
    } catch {
      results.push(`${linkPath} \u4E0D\u5B58\u5728\uFF0C\u8DF3\u8FC7`);
      continue;
    }
    if (!st.isSymbolicLink()) {
      results.push(`${linkPath} \u4E0D\u662F\u94FE\u63A5\uFF0C\u62D2\u7EDD\u5220\u9664`);
      continue;
    }
    fs.unlinkSync(linkPath);
    results.push(`${linkPath} \u5DF2\u89E3\u94FE`);
  }
  emit({ ok: true, results });
}
function cmdAgentsLink(agentName) {
  const registry = loadRegistry();
  if (!fs.existsSync(AGENTS_DIR)) fail(`vault \u4E2D\u4E0D\u5B58\u5728 agents \u76EE\u5F55: ${AGENTS_DIR}`);
  const results = [];
  for (const a of linuxAgents(registry)) {
    if (agentName && a.name !== agentName) continue;
    if (!a.agentsDir) {
      if (agentName) fail(`agent \u672A\u914D\u7F6E agentsDir: ${a.name}`);
      continue;
    }
    fs.mkdirSync(path.dirname(a.agentsDir), { recursive: true });
    const st = linkState(a.agentsDir, AGENTS_DIR);
    if (st === "linked") {
      results.push(`${a.agentsDir} \u5DF2\u94FE\u63A5\uFF0C\u8DF3\u8FC7`);
      continue;
    }
    if (st === "real-dir") {
      results.push(`${a.agentsDir} \u662F\u771F\u5B9E\u76EE\u5F55\uFF0C\u62D2\u7EDD\u8986\u76D6\uFF0C\u8DF3\u8FC7`);
      continue;
    }
    if (st !== "missing") {
      fs.unlinkSync(a.agentsDir);
      results.push(`${a.agentsDir} \u65E7\u94FE\u63A5\u5DF2\u79FB\u9664\uFF08${st}\uFF09`);
    }
    const rel = path.relative(path.dirname(a.agentsDir), AGENTS_DIR);
    fs.symlinkSync(rel, a.agentsDir);
    results.push(`${a.agentsDir} -> ${rel}`);
  }
  emit({ ok: true, results });
}
function cmdAgentsUnlink(agentName) {
  const registry = loadRegistry();
  const results = [];
  for (const a of linuxAgents(registry)) {
    if (agentName && a.name !== agentName) continue;
    if (!a.agentsDir) {
      if (agentName) fail(`agent \u672A\u914D\u7F6E agentsDir: ${a.name}`);
      continue;
    }
    let st;
    try {
      st = fs.lstatSync(a.agentsDir);
    } catch {
      results.push(`${a.agentsDir} \u4E0D\u5B58\u5728\uFF0C\u8DF3\u8FC7`);
      continue;
    }
    if (!st.isSymbolicLink()) {
      results.push(`${a.agentsDir} \u4E0D\u662F\u94FE\u63A5\uFF0C\u62D2\u7EDD\u5220\u9664`);
      continue;
    }
    fs.unlinkSync(a.agentsDir);
    results.push(`${a.agentsDir} \u5DF2\u89E3\u94FE`);
  }
  emit({ ok: true, results });
}
function cmdSync() {
  const steps = [];
  const conflicts = [];
  const record = (cmd, r2) => {
    steps.push({ side: "wsl", cmd, ok: r2.ok, detail: (r2.stderr || r2.stdout || "").trim().slice(-600) });
  };
  record("git add -A", gitRun(["add", "-A"]));
  const st = gitRun(["status", "--porcelain"]);
  if (st.stdout.trim()) {
    record("git commit", gitRun(["commit", "-m", `devhub sync ${(/* @__PURE__ */ new Date()).toISOString()}`]));
  } else {
    steps.push({ side: "wsl", cmd: "git status\uFF08\u65E0\u53D8\u66F4\uFF0C\u8DF3\u8FC7 commit\uFF09", ok: true, detail: "clean" });
  }
  let r = gitRun(["pull", "--rebase", "origin", "main"]);
  record("git pull --rebase origin main", r);
  if (!r.ok) conflicts.push(`wsl pull --rebase:
${(r.stderr || r.stdout).trim()}`);
  r = gitRun(["push", "origin", "main"]);
  record("git push origin main", r);
  if (!r.ok) conflicts.push(`wsl push:
${(r.stderr || r.stdout).trim()}`);
  emit({ ok: conflicts.length === 0, steps, conflicts });
}
function shebangScripts(opts) {
  const out = [];
  if (!fs.existsSync(SKILLS_DIR)) return out;
  for (const s of listSkills()) {
    const scriptsDir = path.join(SKILLS_DIR, s.name, "scripts");
    if (!fs.existsSync(scriptsDir)) continue;
    const visit = (dir) => {
      for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, e.name);
        if (e.isDirectory()) visit(full);
        else if (e.isFile()) {
          try {
            const fd = fs.openSync(full, "r");
            const buf = Buffer.alloc(2);
            fs.readSync(fd, buf, 0, 2, 0);
            fs.closeSync(fd);
            if (buf.toString("utf8") !== "#!") continue;
            if (opts?.onlyMissingExec && fs.statSync(full).mode & 73) continue;
            out.push({
              rel: path.posix.join(s.name, "scripts", path.relative(scriptsDir, full).replace(/\\/g, "/")),
              full
            });
          } catch {
          }
        }
      }
    };
    visit(scriptsDir);
  }
  return out;
}
function cmdFixPermissions() {
  const fixed = [];
  for (const s of shebangScripts()) {
    fs.chmodSync(s.full, 493);
    fixed.push(s.rel);
  }
  emit({ ok: true, fixed });
}
function cmdSelfcheck() {
  const registry = loadRegistry();
  const name = gitRun(["config", "user.name"]);
  const email = gitRun(["config", "user.email"]);
  const origin = gitRun(["ls-remote", "--heads", "origin"]);
  const execIssues = shebangScripts({ onlyMissingExec: true }).map((s) => ({ rel: s.rel }));
  const mntLinks = [];
  for (const a of linuxAgents(registry)) {
    if (a.agentsDir) {
      let st;
      try {
        st = fs.lstatSync(a.agentsDir);
      } catch {
        st = null;
      }
      if (st && st.isSymbolicLink()) {
        try {
          const t = fs.readlinkSync(a.agentsDir);
          const abs = path.isAbsolute(t) ? t : path.resolve(path.dirname(a.agentsDir), t);
          if (abs.includes("/mnt/")) mntLinks.push({ agent: a.name, skill: "(agentsDir)", target: abs });
        } catch {
        }
      }
    }
    const dir = a.skillsDir;
    if (!fs.existsSync(dir)) continue;
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!e.isSymbolicLink()) continue;
      try {
        const t = fs.readlinkSync(path.join(dir, e.name));
        const abs = path.isAbsolute(t) ? t : path.resolve(dir, t);
        if (abs.includes("/mnt/")) mntLinks.push({ agent: a.name, skill: e.name, target: abs });
      } catch {
      }
    }
  }
  emit({
    ok: true,
    identity: { name: name.stdout.trim(), email: email.stdout.trim() },
    originOk: origin.ok && origin.stdout.trim().length > 0,
    execIssues,
    mntLinks
  });
}
function main() {
  const argv = process.argv.slice(2).filter((a) => a !== "--json");
  const cmd = argv[0];
  const flagAgent = (() => {
    const i = argv.indexOf("--agent");
    return i >= 0 ? argv[i + 1] : void 0;
  })();
  switch (cmd) {
    case "scan":
      return cmdScan();
    case "link":
      return cmdLink(argv[1] ?? "", flagAgent);
    case "unlink":
      return cmdUnlink(argv[1] ?? "", flagAgent);
    case "agents-link":
      return cmdAgentsLink(flagAgent);
    case "agents-unlink":
      return cmdAgentsUnlink(flagAgent);
    case "sync":
      return cmdSync();
    case "fix-permissions":
      return cmdFixPermissions();
    case "selfcheck":
      return cmdSelfcheck();
    default:
      fail(`\u672A\u77E5\u547D\u4EE4: ${cmd ?? "(\u7A7A)"}\u3002\u53EF\u7528: scan|link|unlink|agents-link|agents-unlink|sync|fix-permissions|selfcheck`);
  }
}
main();
